### ISSUE TITLE
python3?

### ISSUE THREAD

**Issue by automaticgiant** [ansible/pytest-ansible#15]

**Comment by jlaska** [comment]
No active plans to enable python3 support at the moment.  Welcome to submit PRs to help move things along.

**Comment by bhavikbhavsar** [comment]
We are using pytest-ansible and moving head would like to be supported with python 3. Any effort estimation what would it require for the changes?

**Comment by geetikakay** [comment]
We are looking for python3 support. Rhel8 is totally on python3 and we are heavily using pytest-ansible in our automation tests.

**Comment by jlaska** [comment]
Thanks for the issue!  I would love to get some help with this.  Anyone interested in working on a PR to resolve this issue?

**Comment by geetikakay** [comment]
We are wiling to help to take pytest-ansible to make it python3 compatable.May be a bit guidance is needed.
Do you think we should start testing it with python3 first to see what all parts are broken or need changes?

**Comment by jlaska** [comment]
@geetikakay that sounds like a great idea.  I'd suggest adding various current python3 environments to the `envlist` in `tox.ini`

**Comment by geetikakay** [comment]
@jlaska sure i can start with it.!!

**Comment by jlaska** [comment]
I think we're good now with python3 support.  At least, tests are passing against 3.6.  Please file any py3 issues as new issues.  Thanks!

**Comment by geetikakay** [comment]
Thanks @jlaska ..We will test with python3.
