### ISSUE TITLE
Use ansible-runner as interface to ansible

### ISSUE THREAD

**Issue by kdelee** [ansible/pytest-ansible#32]
This could help us avoid issues like #28, and it has been suggested as an enhancement. Could consult with @benthomasson or other suggested contact for re-design

**Comment by benthomasson** [comment]
Let me know when you want to discuss using ansible-runner for this.   It is the right tool for the job.

**Comment by cidrblock** [comment]
Given the age of this and we're closing it.  If we see major issues related to this in the futre we can reopen/reconsider.
