### ISSUE TITLE
ansible singleton display.verbosity is always overwritten in module dispatcher

### ISSUE THREAD

**Issue by wangxin** [ansible/pytest-ansible#44]
In plugin.py, there is logic to get the singleton object ansible.utils.display::Display() and set its verbosity value according to pytest config option.
```
def pytest_configure(config):
    """Validate --ansible-* parameters."""
    log.debug("pytest_configure() called")

    config.addinivalue_line("markers", "ansible(**kwargs): Ansible integration")

    # Enable connection debugging
    if config.option.verbose > 0:
        if hasattr(ansible.utils, 'VERBOSITY'):
            ansible.utils.VERBOSITY = int(config.option.verbose)
        else:
            from ansible.utils.display import Display
            display = Display()
            display.verbosity = int(config.option.verbose)

    assert config.pluginmanager.register(PyTestAnsiblePlugin(config), "ansible")
```

However, this verbosity is always overwritten in module dispatcher. Take module_dispatcher/v28.py as an example. Below lines will always set display.verbosity to 5 under the hood.
```
        # Pass along cli options
        args = ['pytest-ansible', '-vvvvv', self.options['host_pattern']]
        for argument in ('connection', 'user', 'become', 'become_method', 'become_user', 'module_path'):
            arg_value = self.options.get(argument)
            argument = argument.replace('_', '-')

            if arg_value in (None, False):
                continue

            if arg_value is True:
                args.append('--{0}'.format(argument))
            else:
                args.append('--{0}={1}'.format(argument, arg_value))

        # Use Ansible's own adhoc cli to parse the fake command line we created and then save it
        # into Ansible's global context
        adhoc = AdHocCLI(args)
        adhoc.parse()
```

The fake command line has "-vvvvv" hardcoded. When adhoc.parse() is executed, display.verbosity will be set to 5.

The consequence is that all the ansible connection debug logs are always output.

Is there a way to get around this except patching the code to get rid of the hard coded "-vvvvv"?

**Comment by poornaviswa** [comment]
This hard-coding does result in a lot of output that we cannot control. Can someone suggest a workaround?

**Comment by wangxin** [comment]
Suggest to remove the `'-vvvvv'` in `args` for the fake command. Then the display singleton will use the verbosity setting passed in from actual command line.

**Comment by kdelee** [comment]
@wangxin thanks for the observation.

Sorry for the delayed response!

Today I fixed the CI so we are now in a good place to receive PRs, I'd be happy to review a PR that addresses this

**Comment by AlanCoding** [comment]
I put up https://github.com/ansible/pytest-ansible/pull/53, which is intended to address this. I only did it for the most recent version, because by now, even Ansible 2.8 is relatively old.
