### ISSUE TITLE
⚠️ v3 major work in progress

### ISSUE THREAD

**Issue by ssbarnea** [ansible/pytest-ansible#73]
Please see below:

**Comment by ssbarnea** [comment]
@Ruchip16 You can now start addresing the temporary excludes from https://github.com/ansible-community/pytest-ansible/blob/main/pyproject.toml#L87-L125 -- basically remove one by one while fixing them. You remove the line, run the linter again and change the code to address the issue.

Most of them should be very easy to fix but if you spot some that you cannot figure exactly how to do, skip them and do the others. You can later talk with me and/or @cidrblock and see how to deal with the remaining ones. In fact @shatakshiiii could also give you some hints as she also did the same kind of cleanup work in the past.

**Comment by Ruchip16** [comment]
> @Ruchip16 You can now start addresing the temporary excludes from https://github.com/ansible-community/pytest-ansible/blob/main/pyproject.toml#L87-L125 -- basically remove one by one while fixing them. You remove the line, run the linter again and change the code to address the issue.
> 
> Most of them should be very easy to fix but if you spot some that you cannot figure exactly how to do, skip them and do the others. You can later talk with me and/or @cidrblock and see how to deal with the remaining ones. In fact @shatakshiiii could also give you some hints as she also did the same kind of cleanup work in the past.

cool, am on it!
